name: Build Custom Range
run-name: "Build Custom Range #${{ github.run_number }}"

on:
  workflow_dispatch:
    inputs:
      range:
        type: string
        default: "."
      publish:
        type: boolean
        default: true

jobs:
  run:
    uses: hiconic-os/hiconic.ci.workflows/.github/workflows/range.yaml@main
    secrets: inherit
    with:
      range: "${{ inputs.range }}"
      publish: ${{ inputs.publish }}